### ISSUE TITLE
Provide update command to update the client version

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client#132]
It would be really nice if we could have a command that would update the client version in a project's `package.json` to the latest.

**Comment by ddgenome** [comment]
Isn't that what this is supposed to do https://github.com/atomist/upgrade-client-automation ?

**Comment by cdupuis** [comment]
Not sure that's what this is. Right now it helps with releasing the client project. If it turns out that this project will deliver that, we should somehow make it part of the CLI.

**Comment by ddgenome** [comment]
We have a few other ways to do this now.
