### ISSUE TITLE
Reject command handler with OrgToken as parameter

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client#207]
I accidentally used `    @Secret(Secrets.OrgToken)` in command handler parameters. (It should have been UserToken)

The client started up and registered. When I tried to run the command in Slack, I got "Oops. Something went wrong."

This is impossible for a non-Atomist to debug; I went to our logs to find the error.

Let's change the client library to reject such a command instead of registering it. Or otherwise provide a clear error earlier.

**Comment by cdupuis** [comment]
You use that token secret but you also ha e to use owner mapped parameter in this case. The validation should happen in the api though.
