### ISSUE TITLE
Test errors with proper-lockfile 3.0.1

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client#225]
https://travis-ci.org/atomist/automation-client-ts/builds/345171346

**Comment by ddgenome** [comment]
Can't reproduce

**Comment by cdupuis** [comment]
Upgrade to latest proper-lockfile.

**Comment by ipcrm** [comment]
It appears this test failure was due to this breaking change in proper-lockfile: https://github.com/moxystudio/node-proper-lockfile/commit/b1d43e525418d74d6fa7cfa246e6451b3cbdd485

This was prior to the 3.0.1 release.

**Comment by ipcrm** [comment]
After further review, it looks like the code that requires `proper-lockfile` can be deprecated.
