### ISSUE TITLE
Make it possible to use graphql queries & fragments from dependencies

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client#313]
We have duplicated graphql files from sdm into sdm-core and sample-sdm etc.
There should be a way to run these queries that are defined in upstream libraries, downstream

**Comment by cdupuis** [comment]
I wonder if that should already be possible with the current way of being able to specify the locations of the graphql folder. I'll give it a try,

**Comment by cdupuis** [comment]
If we don't have graphql folder, generating types would also fail.
