### ISSUE TITLE
Add registration valdidation

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client#319]
Issue moved from atomist/sdm#397

Created by @johnsonr at 2018-05-31T22:55:06Z:

Duplicate handlers and registrations should be detected. Enforcement should probably be by name.

**Comment by lievendoclo** [comment]
Indeed, this should fail fast. +1

**Comment by ipcrm** [comment]
+1

**Comment by cdupuis** [comment]
- 1

I think this type of verification belongs into the backend api layer as that is the place for really validate overlapping intents etc.

**Comment by cdupuis** [comment]
```
    "parameters": [{
      "name": "envVarValueHolder",
      "pattern": "^.*$",
      "required": true,
      "displayable": false,
      "default_value": "DEFAULT",
      "display_name": "envVarValueHolder"
    }
```
^ the above parameter fails too.

**Comment by cdupuis** [comment]
Other use cases:

* duplicate intents
* https://github.com/atomist/automation-client/issues/207
