### ISSUE TITLE
Ingester Registration Warnings

### ISSUE THREAD

**Issue by kbristow** [atomist/automation-client#404]
When trying to register ingesters in `atomist.config.ts` using the command
```javascript
ingester("Shared.graphql")
```

where `Shared.graphql` is a file containing the following for example:
```graphql
type GluonTenantId {
    tenantId: string
}

type SlackIdentity {
    screenName: string
    userId: string
    teamChannel: string
}

type BitbucketProject {
    id: string
    key: string
    name: string
    description: string
    url: string
}
```

Starting the client yields the warning:
`WARNING: No ingester graphql operation found for name 'Shared.graphql'. Falling back to file name lookup. Support for file name lookup will be removed in a future release.`

**Comment by cdupuis** [comment]
Thanks, looking into this today.

**Comment by cdupuis** [comment]
@kbristow looks like if you use ` GraphQL.ingester("GluonTenantId");` it will work without warning.

I don't like the fact that addressing one type loads the whole lot, buts maybe something we can address separately.

**Comment by kbristow** [comment]
What is the recommended practice here? Should each type have its own file? Or should I use the above suggestion until the issue is addressed differently?

**Comment by cdupuis** [comment]
Yea, use the one type to load whole bunch until we figure out a nicer way. Ok?

**Comment by kbristow** [comment]
Yep that is cool with me. Thanks.
