### ISSUE TITLE
Pretty easy to import the wrong `subscription` function

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/automation-client#412]
When I'm creating new event handlers, I keep importing the wrong subscription function:

I wonder if there's value in renaming one of them.

```
import { subscription } from "@atomist/automation-client/lib/graph/graphQL";
import { subscription } from "@atomist/automation-client/lib/internal/graph/graphQL";
```

**Comment by ddgenome** [comment]
You should only be importing from the index. In this case, import GraphQL from the index and use GraphQL.subscription

**Comment by slimslenderslacks** [comment]
Ah cool, that's important.

In this case, I don't think the @atomist/automation-client has a subscription in the index so maybe it's not needed any longer.  I've been defining EventHandlers using this function, and that could be the problem.

**Comment by cdupuis** [comment]
The import should be `import { GraphQL } from "@atomist/automation-client";` and then use `GraphQL.subscription` etc. 

Can we close this here?

**Comment by slimslenderslacks** [comment]
Yes, this looks okay now.
