### ISSUE TITLE
Logging Setting can cause SDM startup hangs

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client#435]
Issue moved from atomist/sdm#637

Created by @ipcrm at 2018-12-20T22:20:34Z:

Improperly configuring your logging setting in client config will prevent SDM startup.  Any invalid setting will cause the behavior:

```json
{
...
 "logging": {
    "level": "foo"
  }
}
```

**Comment by cdupuis** [comment]
Urgh, that’s terrible. Thanks for raising this @ipcrm.

**Comment by cdupuis** [comment]
@ipcrm, it appears as if the SDM/client continues to operate. It just doesn't log anything any more. I'll put some validation in that would prevent an invalid log level.

**Comment by ipcrm** [comment]
Thx!
