### ISSUE TITLE
Sending CommandHandlerResponse messages with empty channel

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/automation-client#462]
VERY low priority but we recently noticed that it's possible to create CommandHandlerResponses where one of the `destination` `channel`s is empty `{}` (there must be either a `name` or an `id`).  

The chatops delivery channels are being updated to log error messages but there could be the possibility for a runtime error before sending the message.  A message with an empty channel is undeliverable.

```
{:destinations [{:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}} {:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}} {:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}} {:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}} {:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}} {:user_agent "slack", :slack {:team {:id "TCVEPK0F7"}, :channel {}}}]}
```

**Comment by slimslenderslacks** [comment]
@ipcrm did have some context on exactly what he was doing when this occurred.  He ended up fixing a bug in his code so this is just to make sure that we handle the error more gracefully.

**Comment by cdupuis** [comment]
Spoke to @ipcrm and he's not able to reproduce this any more. Feel free to reopen with a test case.
