### ISSUE TITLE
BitBucketServerRepoRef support cloning from specific branch

### ISSUE THREAD

**Issue by ipcrm** [atomist/automation-client#482]
Add functionality to BitBucketServerRepoRef to support cloning (starting point) from a particular branch.   Currently, only master is supported.  Tested supplying this as SHA property but that doesn't not work currently.

**Comment by cdupuis** [comment]
@lievendoclo could you please take a look at that?

**Comment by lievendoclo** [comment]
👍

**Comment by cdupuis** [comment]
@lievendoclo I have the feeling this is closed. Can you confirm.

**Comment by lievendoclo** [comment]
I think @ipcrm merged this in another branch, but I'll check with him.
