### ISSUE TITLE
Automatically redact HTTP authentication info in chat messages

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client#526]
Issue moved from atomist/sdm#718

Created by @ipcrm at 2019-04-29T13:48:25Z:

Potentially using `AutomationEventListener.messageSending`, apply a regex to detect anything that looks like `http[s]://user:pass@host[:port]/.*` and replace it with `http[s]://user:[REDACTED]@host[:port]/.*` in the chat message.  This will prevent any authentication info from ever getting sent to a chat platform if the creator of that message is not parsing it themselves.

**Comment by ipcrm** [comment]
Another pattern to look for: `https://<token>:x-oauth-basic@host[:port]`
