### ISSUE TITLE
MessageClient reply in thread

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/automation-client#538]
Was discussing this one with @ipcrm.  

The current `reply` will respond in a thread if the message already arrived _from_ a thread.  However, the user may want to specify that the message start a new thread if the command began from an unthreaded channel message.

Slack:
This can be done by using the `ts` of the current CommandHandlerRequest

```
{
  "source": {
    "slack": {
      "message": {
        "ts": "xxxxxx"
      }
    }
  }
}
```  
and copying it into the thread_ts (which will be null if the message has come from an unthreaded channel)

```
{
  "source": {
    "slack": {
      "thread_ts": null,
    }
  }
}
```  
MSTeams: nothing to do
Web:  nothing to do

Supporting this allows a command handler with zero parameters to reply in a slack thread.

**Comment by cdupuis** [comment]
Already supported. Nothing to do.
