### ISSUE TITLE
Atm-gql-gen fails if node_modules is not in $PWD (e.g. using lerna + hoisted packages)

### ISSUE THREAD

**Issue by XertroV** [atomist/automation-client#629]
AFAIK `node_modules` can be in the package root dir or any parent directory. One case where this applies is using lerna for a multirepo + hoisted packages. Most packages are in /node_modules but packages each have their own node_modules in /packages/<PKG_NAME>/node_modules.

Using an SDM in one of the packages results in atm-gql-gen failing:

```
$ DEBUG=* npx atm-gql-gen --verbose
Failed to find any GraphQL type definitions in: /path/to/myrepo/packages/sdm-bootstrap/node_modules/@atomist/automation-client/lib/graph/schema.json - undefined
Generating GraphQL types failed: undefined
```

The file does exist at ` /path/to/myrepo/node_modules/@atomist/automation-client/lib/graph/schema.json` though.

I have worked around it for the moment but maybe importing the json file via TS would fix this?

**Comment by cdupuis** [comment]
@XertroV, would it be possible to get a few more details on how to set up some projects to make this error appear? I struggle to fully understand what is going wrong here. Thanks.

**Comment by XertroV** [comment]
@cdupuis for sure. I can privately share a full example, but I *think* it might be sufficient to take a normal SDM, put everything but package.json and node modules in a subfolder, then try to run "npx atm-start" from the subfolder.

**Comment by XertroV** [comment]
Ahh wait not atm-start; I think npm start has compile and stuff before atm-start. Anyway triggering the graphql compilation however it's done.

**Comment by cdupuis** [comment]
Let me try that. Thanks for the instructions.

**Comment by cdupuis** [comment]
This is fixed in master now.

**Comment by XertroV** [comment]
Awesome, thanks!
