### ISSUE TITLE
Library isn't found for imports

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client#649]
I see that index.ts has been deleted on the latest master

which causes typescript to say that "@atomist/automation-client" is not found when I try to import something from it

What is the intention there? Should we use deep imports for now?

**Comment by ddgenome** [comment]
Yes, deep imports for now, or use a 1.8 version. The plan is to remove automation-client as a dependency separate from sdm, and export the relevant parts of automation-client in sdm.

**Comment by ddgenome** [comment]
If you need anything else, please reopen.
