### ISSUE TITLE
Support for .env files

### ISSUE THREAD

**Issue by rudy750** [atomist/automation-client#656]
this would be helpful for local development and configuration in general. I assumed support was there and was trying to use it to set:

ATOMIST_CONFIG_PATH=./atomist.config.json
ATOMIST_MODE=local

https://www.npmjs.com/package/dotenv

**Comment by cdupuis** [comment]
You can use our config profile support for this.

Eg. starting an SDM with the following command will load the `client.config.json` from your `~/.atomist` directory and overlay that with the contents of the `client.config-localhost.json` file.

```
$ atomist start --profile localhost
```

If you want support for `dotenv`, it should be possible to add the dependency and required call to initialise it to the top of your `index.js`.
