### ISSUE TITLE
Add ability to add an empty directory to a Project

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client#86]
May not be accessible in `InMemoryProject`, but should still be preserved through transformations.

**Comment by johnsonr** [comment]
Still need ability to populate an `InMemoryProject` from a file based project and preserve empty directories

**Comment by johnsonr** [comment]
See pending test

```
it.skip("copies in memory project including empty directory and copies back")
```

**Comment by ddgenome** [comment]
What's the use case here? Git won't respect empty directories.
